<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/stylesheet.css">
    <link rel="stylesheet" href="../css/style.css">
    <title>Portfolioo</title>
</head>
<body>  
    <header>
        <title>About</title>
        <h1><strong>ABOUT</strong></h1>
        <a href="phpinfo.php">PHP</a>
        <a href="location.php">HASAKI</a>
        <a href="port.php">Me</a>
    </header>
 
    <form action="about.php" method="post">
            <button type="submit" name="menu" value="Toggle showAbout">Menu</button>
        </form>
    <div class="col-6-md">
        <a href="index.php" class="btn btn-success" title="BACK TO LIST">Back</a>
    </div>
</body>
</html>
