<!DOCTYPE html>
<html>

<head>
    <title>Hasaki Beauty & Clinic</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <link rel="stylesheet" href="../css/stylesheet.css">
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
    <style>
        #map {
            height: 400px;
            width: 100%;
        }
    </style>
</head>

<body>
    <h3>Hasaki Beauty & Clinic</h3>
    <div id="map"></div>
    <script>
        var map = L.map('map').setView([10.7949582, 106.6589721], 25);
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href = "https://www.openstreetmap.org/copyright ">OpenStreetMap</a> contributors'
    }).addTo(map);
        var marker = L.marker([10.7949582, 106.6589721]).addTo(map)
            .bindPopup('29 Hoàng Việt, Phường 4, Tân Bình, Hồ Chí Minh, Vietnam.<br> Hasaki Beauty & Clinic.')
            .openPopup();
        // var map = L.map('map').setView([10.7949582, 106.6589721], 40);
        // L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        //     attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        // }).addTo(map);
        // var marker = L.marker([10.7949582, 106.6589721]).addTo(map)
        //     .bindPopup('29 Hoàng Việt, Phường 4, Tân Bình, Hồ Chí Minh, Vietnam.<br> Hasaki Beauty & Clinic.')
        //     .openPopup();
    </script>
    <div class="btn-location">
        <a href="index.php" class="btn btn-default btn-lg fa fa-arrow-left" title="BACK TO LIST">Back</a>
    </div>
</body>

</html>