<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/style.css">
    <link rel="stylesheet" href="../css/stylesheet.css">

    <title>Portfolioo</title>
</head>
<body>
<header>
    <h1>Vu Nha Luan's Portfolio</h1>
</header>

<div class="container">
    <div class="profile">
    <a href="https://ibb.co/XbxHKmS"><img src="https://i.ibb.co/dr4ZVnG/file-go-c-Luan.jpg" alt="file-go-c-Luan" border="0" /></a>
        <h1>Vu Nha Luan</h1>
        <p>Fresher Web Developer</p>
        <p>Hobbies: Playing sports, Listening to music</p>
        <form method="post" action="https://imagekit.io/does-not-exists" enctype="multipart/form-data"></form>
        <input type="file" id="avatar" name="avt" accept="image/*" capture="camera">
        <button>Upload</button>
        <div id="fileInfo"></div>
    </div>

    <div class="portfolio">
        <h2>My Work</h2>
        <div class="portfolio-item">
            <div>
                <h3>Project 1</h3>
                <p>Description of project 1.</p>
            </div>
            <div>
                <h3>Project 2</h3>
                <p>Description of project 2.</p>
            </div>
            <div>
                <h3>Project 3</h3>
                <p>Description of project 3.</p>
            </div>
            <div>
                <h3>Project 4</h3>
                <p>Description of project 4.</p>
                <iframe src="http://127.0.0.1" title="description" width="300px" height="300px"></iframe>
            </div>
        </div>
    </div>
</div>

    <div class="fluid-layout">
        <input type="text" name="account">
        <input type="password" name="password">
        <input type="submit">
        <div class="col-6-md">
        <a href="index.php" class="btn btn-success" title="BACK TO LIST">Back</a>
    </div>
    </div>
<footer>
    <p>&copy; 2024 Vu Nha Luan</p>
</footer>
</body>
</html>

<script>
    document.getElementById('fileInput').addEventListener('change', function(event) {
        var file = event.target.files[0];
        var fileInfo = `
        <p>File Name: ${file.name}</p>
        <p>File Size: ${file.size} bytes</p>
        <p>File Type: ${file.type}</p>
        `;
        document.getElementById('fileInfo').innerHTML = fileInfo;
    });
</script>